### ISSUE TITLE
tlog.app/go/loc update

### ISSUE THREAD

**Issue by nikandfor** [teler-sh/teler-waf#207]
Hi,

I see you use `tlog.app/go/loc` library, and first of all, thank you, it's a pleasure for me someone uses my code.

Because of changes in the language the version of the library you use will not compile with go1.23 (the next release). The fix is already landed into the library, please consider updating it to the latest version, which is v0.7.0 now.

I'd happy to answer any questions if they arise. And once again, thank you for using the lib.

**Comment by dwisiswant0** [comment]
Hi, thanks for the information. So, it looks like #206 is safe to merge.
